stages:
  - test
  - build
  - deploy

variables:
  IMAGE: $DOCKER_USER/flask-example


# TEST STAGE

test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8


# BUILD STAGE

.build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE:$TAG .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $IMAGE

build dev:
  extends: .build
  only:
   - /devel/
  environment:
    name: dev

build prod:
  extends: .build
  only:
   - /stable/
  environment:
    name: prod

build homolog:
  extends: .build
  only:
   - /master/
  environment:
    name: homolog

# DEPLOY STAGE

.deploy:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --service $SERVICE_NAME
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --rancher-key $RANCHER_ACCESS_KEY
            --rancher-secret $RANCHER_SECRET_KEY
            --rancher-url $RANCHER_URL"

deploy dev:
  variables:
    SERVICE_NAME: dev-flask
  extends: .deploy
  only:
    - /devel/
  environment:
    name: dev

deploy homolog:
  variables:
    SERVICE_NAME: hm-flask
  extends: .deploy
  only:
    - /master/
  environment:
    name: homolog

deploy prod:
  variables:
    SERVICE_NAME: flask
  extends: .deploy
  only:
    - /stable/
  environment:
    name: prod